// <auto-generated />
namespace NawafizApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrequiredforroomrecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrequiredforroomrecords));
        
        string IMigrationMetadata.Id
        {
            get { return "202103062343189_add-required-for-room-records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
