// <auto-generated />
namespace NawafizApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addshiftstousers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addshiftstousers));
        
        string IMigrationMetadata.Id
        {
            get { return "202103022358447_add-shifts-to-users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
