// <auto-generated />
namespace NawafizApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kok66 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kok66));
        
        string IMigrationMetadata.Id
        {
            get { return "202102111423503_kok66"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
