//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NawafizApp.Services.FromMysql {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FromMysql.ITest1Service")]
    public interface ITest1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest1Service/add", ReplyAction="http://tempuri.org/ITest1Service/addResponse")]
        int add();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest1Service/add", ReplyAction="http://tempuri.org/ITest1Service/addResponse")]
        System.Threading.Tasks.Task<int> addAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest1Service/List", ReplyAction="http://tempuri.org/ITest1Service/ListResponse")]
        System.Data.DataTable List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITest1Service/List", ReplyAction="http://tempuri.org/ITest1Service/ListResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITest1ServiceChannel : NawafizApp.Services.FromMysql.ITest1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Test1ServiceClient : System.ServiceModel.ClientBase<NawafizApp.Services.FromMysql.ITest1Service>, NawafizApp.Services.FromMysql.ITest1Service {
        
        public Test1ServiceClient() {
        }
        
        public Test1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Test1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add() {
            return base.Channel.add();
        }
        
        public System.Threading.Tasks.Task<int> addAsync() {
            return base.Channel.addAsync();
        }
        
        public System.Data.DataTable List() {
            return base.Channel.List();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListAsync() {
            return base.Channel.ListAsync();
        }
    }
}
